### ISSUE TITLE
Synology NAS installation tutorial (or package)

### ISSUE THREAD

**Issue by ghost** [styxit/HTPC-Manager#113]
Hi.

I would like to install HTPC manager on my Synology NAS. I have found a couple of issues about that:
- https://github.com/styxit/HTPC-Manager/issues/12
- https://github.com/styxit/HTPC-Manager/issues/93

But finally no real conclusion and no ready to use material. I would expect a tutorial in the installation page:

http://htpc.io/installation.html

This tutorial could be just a description of the steps specific to the Synology, or even better, based on a package. This last option is appealing, but the package should be clean, meaning it should be integrated with [DSM](http://www.synology.com/en-uk/dsm/index). If there is such a package in progress, I could give a hand. Otherwise I can write a tutorial for a standard command lines installation.

Hosting HTPC manager on a NAS is really meaningful, so my guess is that such a feature would be used by many.

**Comment by imro2** [comment]
I installed it on my synology nas and successfully ran one upgrade. However now it is showing that it is 109 versions behind and won't upgrade. The main reason for upgrade is headphones support.

**Comment by Hellowlol** [comment]
@imro2 If you want to use hp you need to use my work. There was some request for a custom package https://github.com/SynoCommunity/spksrc/issues/1441#issuecomment-109931558, there is also a pr awaiting review. Until thats merged you can use this guide https://github.com/Hellowlol/HTPC-Manager/wiki/Installing-HTPC-on-Synology-NAS to switch to my fork. Please note the issues with that install method.
