### ISSUE TITLE
Plex integration no longer working with latest Plex

### ISSUE THREAD

**Issue by zbuc** [styxit/HTPC-Manager#317]
It looks like the root page of Plex Media Server won't respond without authorization any more, so the test for adding the server (and media listing) aren't working.

I verified by making a similar request as to what it looks like `modules/plex.py` would make via curl:

```
~ $ curl -H "X-Plex-Username: myusername" -H "Accept: application/json" http://plex.local:32400/
<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>%
```

Logs:

```
2014-12-10 20:27:10 :: modules.plex :: ERROR :: Unable to contact Plex via http://plex.local:32400
2014-12-10 20:32:10 :: modules.plex :: ERROR :: Unable to fetch currently playing information! Exception: HTTP Error 401: Unauthorized
```

I haven't had a chance to dig deeper and see if it is simple to patch

**Comment by needo37** [comment]
I just submitted my change...

https://github.com/styxit/HTPC-Manager/pull/323

**Comment by zbuc** [comment]
@needo37 your patch works for me, I am able to connect to my Plex server and view my media in HTPC Manager

**Comment by styxit** [comment]
@Hellowlol Do you also agree on merging #323 ?

**Comment by Hellowlol** [comment]
Well i havnt checked that it solved the issue regarding plex home but i have tested that it dosnt messes up things for non plex home users. So i would merged this

**Comment by mpguidry** [comment]
i still cant connect to my plex

**Comment by Hellowlol** [comment]
Are you using ssl?

**Comment by syrys** [comment]
Sorry to dig up this thread: but this is still an issue.

I recently installed HTPC Manager and tried connecting to my plex, but no luck.

This is what i see in Logs:
````
2016-10-05 16:59:25	modules.plex	ERROR	Unable to contact Plex via http://192.168.1.50:32400 error HTTP Error 401: Unauthorized
````
I provided my correct plex username and password. I left the mac addr field blank as i wasent sure what that was for. All other fields were filled correctly. Also the url above (`http://192.168.1.50:32400`) is also correct and it will open up my plex.

**Comment by Hellowlol** [comment]
@syrys Tried a restart of htpc manger?

**Comment by syrys** [comment]
@Hellowlol i thought you were joking, but that actually fixed it. But why/how?

**Comment by Hellowlol** [comment]
Depends, are you using my fork or this version?

**Comment by morpheus65535** [comment]
Ok... it's freaking... It also work for me. I'm using @Hellowlol version...
