### ISSUE TITLE
Samsung TV remotes

### ISSUE THREAD

**Issue by elRadix** [styxit/HTPC-Manager#328]
I have 2 samsung tv, is there a possibility to add a second IP addresses ?

**Comment by Hellowlol** [comment]
Well isn't there 2 in the drop down  menu?

**Comment by Hellowlol** [comment]
Btw, wrong repo.

**Comment by elRadix** [comment]
yes, but on the main top menu I can only show 1 remote, I want to show 2 tv remotes if that is possible

**Comment by Hellowlol** [comment]
@elRadix Please close this issue and make a new one in my repo. Styxit didn't want a remote in is version
