### ISSUE TITLE
Feature Request - Calendar View for Sickbeard "Next Aired"

### ISSUE THREAD

**Issue by gcoan** [styxit/HTPC-Manager#330]
Not sure if this is possible in HTPC-Manager or dependent on SB itself but it would be sweet to see the Next Aired section in a calendar view instead of a list view :-)

**Comment by Hellowlol** [comment]
There is no limit, it's just a pita to code.

**Comment by gcoan** [comment]
How about support for Sonarr then?  :-)  I've switched (because of its awesome calendar and stuff)

**Comment by Hellowlol** [comment]
Sonarr is supported in my fork. You can use that one until it is added

**Comment by gcoan** [comment]
Cheers!
