### ISSUE TITLE
Multiple newznab server support

### ISSUE THREAD

**Issue by kooimens** [styxit/HTPC-Manager#331]
Would be great to have an option to add multiple newznab servers for searching NZB's.

**Comment by Hellowlol** [comment]
I have been thinking of adding support for NZBmegasearcH or just change it so its possible to add more newnab sites. I need to find a decent second site so i have something to test with. Do you have any recommendations?

**Comment by kooimens** [comment]
usenet-crawler.com ?

**Comment by Hellowlol** [comment]
Damn, that site was ugly. Seems to work ok tho. Thanks!

**Comment by kooimens** [comment]
Yeah, really ugly, but it rocks. Most NZBs in database of almost all the newznab indexers. And many api calls a day, all free.
