### ISSUE TITLE
Dropdown menu for "Other apps" too short on mobile device (sometimes)

### ISSUE THREAD

**Issue by kooimens** [styxit/HTPC-Manager#333]
I use 4 normals apps (sab, couch, sick and plex) and 9 "other apps". The dropdown menu on my mobile devices shows only the four normal apps and 6 (and a half)  "other apps" if I click 'Other' and the menu come down. Then i can't see the remaining 2 (and a half) "other apps" and the link to github, check for update etc. The next thing it shows is my dashboard. However, if i go back to my home screen of the app (right-corner, click) and re-open with right-corner, click and select 'Other' again, then it's fixed and it shows everything it should show.

**Comment by Hellowlol** [comment]
I don't use other links much but I can corfi me this bug

**Comment by Hellowlol** [comment]
@kooimens Can you try this branch? Seems to be working fine here now, but since it kinda works sometime it would be great if you could confirm

**Comment by kooimens** [comment]
That one is working as it should! Thanks

**Comment by Hellowlol** [comment]
Gonna send a pr later to correct this

**Comment by styxit** [comment]
Thanks!
