### ISSUE TITLE
Search Box Is Offset In Slate Theme

### ISSUE THREAD

**Issue by brando56894** [styxit/HTPC-Manager#336]
For some reason, when the Slate theme is selected the search box is on the next row down from everything else, which then covers up the header of the following section, for example, the NZBget speed.

http://www.imagebam.com/image/91c56d387249588

This happens at all resolutions and with all browsers.

**Comment by Hellowlol** [comment]
See https://github.com/styxit/HTPC-Manager/issues/242

**Comment by brando56894** [comment]
Interesting. I disabled XBMC and everything is good again, thanks.
