### ISSUE TITLE
Add sonarr support

### ISSUE THREAD

**Issue by mostlydave** [styxit/HTPC-Manager#337]
Please add sonarr support to the main branch, I'm running this in a docker in unraid, so I need it added to the auto update for it to be usable.

**Comment by Hellowlol** [comment]
Doesnt the nzbdrone variable work in the docker?

**Comment by mostlydave** [comment]
I'm sure it would, but unraid dockers are super easy to setup because they are pulled from a repository. I don't have the knowledge to switch branches myself.

I also don't understand why sonarr support hasn't been added to the main version, it's pretty popular from what I can see. There's multiple requests for it here and your version of it, so why not just add it already?

**Comment by Hellowlol** [comment]
Its already included in my version thats why i asked regarding your docker :)

**Comment by mostlydave** [comment]
I know I saw it's in your version, and obviously other people would like sonarr support added, so why do we need more than one version? Why don't we just add sonarr support to the main version and users can pick the apps they use from the settings?

**Comment by styxit** [comment]
I know there used to be a Pul request to add Sonarr. At the time i was not able to merge it. If there is another PR for sooner i will merge it.

**Comment by mostlydave** [comment]
If you guys could make this happen it would be great!

**Comment by Hellowlol** [comment]
Well in my case styxit and i dont have the same view on what should and shouldnt be included in htpc manager. Thats the great thing about open source if there something you don't like/  want to add you can. The Bad thing is fragmentation. Ideally I would like to merge all my work with styxit and just continue to do prs but that isn't a option.

I hope it gets added, I made the nzbdrone module just because a lot of users requested it.

**Comment by mostlydave** [comment]
Ok, what's the problem here, it looks like he just asked you for a PR so it can be merged, why isn't that an option?

**Comment by Hellowlol** [comment]
To be fair he didn't ask me for a pr. I made the module, I did pr the pr. It was left unmerged for one and a half month it could have been merged with 4 clicks from a cellphone. I did some cleanup regarding my branches, I didn't know that the pr would close aswell. I don't have that branch anymore. 

So in short if no one is willing to do the bare minimum work of copying 8 files and add 2 lines to one file it isn't really wanted..

**Comment by mostlydave** [comment]
He literally asked in this issue 2 hours ago for a pr and he'll merge it, I see you're offended that it wasn't merged before but, you're only denying a feature that the rest of us would like by not doing it, I'm asking you to please do whatever you need to on your end so that your version with sonarr support can be merged with the the main version and everyone can choose to use sonarr in the main branch if they like.

**Comment by Hellowlol** [comment]
Let me be clear: I'm not offended. Styxit has explained why he didn't have time before that's fine. We are all doing this in our spare time and sometimes there aren't enought hours in a day to get everything done.

Mostlydickish behavior like saying I'm denying anyone anything is bullshit and is just making me pissed.

I think I have done more then enough. Here is the old pr: https://github.com/styxit/HTPC-Manager/pull/297
Roll up your sleeve and start copy pastin..

Your comment just ensured that I'm never doing it.

/nuff said

**Comment by mostlydave** [comment]
Let me be clear, no one made you come in here and start suggesting that multiple versions are the answer to sonarr support.

If you had no intention of doing a pr why did you even come in and comment on my issue? I'm new here but it seems to me like you have had some kind of problem with this project and styxit long before I showed up. 

I just wanted to come in and say I would love to see sonarr support, sorry if that got your diaper in a twist.

**Comment by Hellowlol** [comment]
No problem with styxit just your behavior :), happy hacking
