### ISSUE TITLE
S.M.A.R.T not correctly configured.

### ISSUE THREAD

**Issue by yungfras** [styxit/HTPC-Manager#346]
Hi, I have download smartontools for windows and have installed but I still get this error. S.M.A.R.T not correctly configured. smartmontools Required package 'smartmontools' is not installed, or 'smartctl' component is not on the system path. Please install and try again.

Please help guys. I'm running Windows 8.1 Pro WMC edition.

**Comment by yungfras** [comment]
i posted this in the wrong area.

**Comment by hpbrad** [comment]
hey did you end up figuring out what was wrong? im having the same issue

**Comment by Hellowlol** [comment]
As he's mention he posted in the wrong area. But in short: start the shell/cmd with admin rights and you need to set the path smarttlc to your environment path. I'll replace that message with a link to a guide on how to fix it

**Comment by BelgarionNL** [comment]
where the guide? also running into this issue.

**Comment by Hellowlol** [comment]
@BelgarionNL are you also using windows?

**Comment by BelgarionNL** [comment]
yes sir. windows 10! I tried 32 bit and 64 bit but its not working.

**Comment by Hellowlol** [comment]
@BelgarionNL See https://github.com/Hellowlol/HTPC-Manager/wiki/Smartmontools-windows-installation-guide If you have any issues please open a issue in my repo.

**Comment by jiBYo** [comment]
Guide for Ubuntu Server?

**Comment by Hellowlol** [comment]
Nope, sorry my man. You can see if you can use something from https://github.com/Hellowlol/HTPC-Manager/wiki/Debian-Wheezy-%28Raspberry%29-Smartmontools-5.42--Installation
