### ISSUE TITLE
Headphones test fail

### ISSUE THREAD

**Issue by yungfras** [styxit/HTPC-Manager#348]
Headphones won't pass a test. i have verified my values are correct by using a android app to log in to Headphones and it works but it doesn't work in HTPC manager.

**Comment by Hellowlol** [comment]
This is the wrong repo, headphones, smartmontools. Please make them on the correct repo after your have read issue guidelines.

**Comment by yungfras** [comment]
Thanks. I'm a newbie. Where would I post to get help with Headphones and smartontools not syncing in HTPC manager?

**Comment by Hellowlol** [comment]
https://github.com/Hellowlol/HTPC-Manager

**Comment by yungfras** [comment]
Thank you.
