### ISSUE TITLE
Downloads on dashboard

### ISSUE THREAD

**Issue by damiantje99** [styxit/HTPC-Manager#351]
Hi,

Is it possible to have the current downloads listed on the dashboard?
It would be much faster then going to the downloading tab.

Kind Regards

**Comment by Hellowlol** [comment]
What downloading tab are you talking about? Do you mean inside the module?

**Comment by styxit** [comment]
That would require a constant refresh of the queue on the dashboard. Could become slow if you have multiple download apps configured.

**Comment by Hellowlol** [comment]
I agree, its would be loads of work and would be slow. Just to give you a idea say 150 ms * downloadclients + 100 ms processing + 100 ms http call. Then you have to deal with designing a common js response for all the clients and handle timeouts, connection errors etc.

**Comment by damiantje99** [comment]
Ah, didn't think about that! Guess this question is answerd :)

**Comment by Hellowlol** [comment]
A easier solution would be to make one for each download module. Like @ mwariz did for the qbittorrent module
