### ISSUE TITLE
Feature Request: Run / Execute scripts & programs on server

### ISSUE THREAD

**Issue by noobydp** [styxit/HTPC-Manager#358]
Hey styxit,

Any chance we can get a feature to execute scripts on the server?
I'm thinking a simple list like the Other Apps / Custom URL section in settings, but specify a program / script that exists locally on the server?

I have previously forked HTPC-Manager and bastardized services.py to do this but it's pretty poor code (and I don't understand most of your code anymore). 
I used a simple subprocess and / or os.system call which seemed to work on windows and Linux hosts.

Thanks :)

**Comment by Hellowlol** [comment]
TIP: you can start htpc manger with --shell and have access to a cli in the stats module. Its not the same, but you can invoke scripts from there until someone does your request.
