### ISSUE TITLE
HDD Disk Monitoring

### ISSUE THREAD

**Issue by wreuel** [styxit/HTPC-Manager#371]
Hello everyone,

I have a HTPC installed in my FreeNAS; and I have mounted two other HD in the JAIL where the HTPC is installed, but the two new is not appearing in the DISK management, do I need to do some configuration??

They are mounted as:
/mtn/Movies
/mnt/TVSHOWS

I didn't find a better place to ask!

**Comment by Hellowlol** [comment]
do mean the disk tab in computer star module? Can you take a screenshot of computer stats settings? Tried restarting htpc manager?

**Comment by wreuel** [comment]
Here, I have two more HDD but they are not visible here!

![captura de tela 2016-03-05 15 41 32](https://cloud.githubusercontent.com/assets/6828665/13549647/d908296a-e2e8-11e5-8730-e475e29a83bf.png)

**Comment by Hellowlol** [comment]
Logs? Screenshot of computer stats settings module. Any console errors?

**Comment by wreuel** [comment]
Follow attached the log, and the settings/system info screenshot!

Thank you @Hellowlol  for helping me!

![captura de tela 2016-03-06 10 32 35](https://cloud.githubusercontent.com/assets/6828665/13554481/9409ca7c-e387-11e5-9165-95ff4e725be9.png)
[htpcmanager.txt](https://github.com/styxit/HTPC-Manager/files/160336/htpcmanager.txt)

**Comment by Hellowlol** [comment]
You log is really messy! Can you please close this isse and open a new one in my repo. Read the issue guidelines first and the parse the response from http....../stats/disk_usage to a gist.

**Comment by wreuel** [comment]
Close to open the https://github.com/Hellowlol/HTPC-Manager/issues/437
