### ISSUE TITLE
"S.M.A.R.T not correctly configured." - smartmontools problem

### ISSUE THREAD

**Issue by ujellyx** [styxit/HTPC-Manager#372]
I followed this guide to setup HTPC Manager but can't seem to get S.M.A.R.T. status to work:
http://www.htpcguides.com/install-htpc-manager-windows/

I installed smartmontools (64bit) and checked to PATH option during installation. I also used that powershell-command, just to make sure. But it still won't work - i always get the following error:
> Required package 'smartmontools' is not installed, or 'smartctl' component is not on the system path. Please install and try again.

I'm on WIndows 10 64bit, latest HTPC Manager, Python 2.7 and latest smartmontools (smartmontools-6.5-0-20160311-r4231.win32-setup).
What am i doing wrong?

**Comment by Hellowlol** [comment]
Please Close this issue. This version does not support smart
